
version: '3'
services:
  app:
    container_name: node-mariya-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    restart: always
